<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="MetadataExtractor" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="EasyImageImporter.Core.Tests" />
  </ItemGroup>
</Project>
